-- Seed email_logs with 30 days of local test data.
-- All timestamps are relative to NOW so the activity chart always shows recent data.
-- Idempotent: removes previous seed rows before inserting.

DELETE FROM email_logs WHERE id LIKE 'seed-%';

-- ── Day 0 (today) ────────────────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-001', 'sent',    '["alice@gmail.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',          'Welcome to Acme',                  '<seed-001@acme.io>', NULL, NULL, CAST(unixepoch('now','-1 hours')*1000 AS INTEGER), CAST((unixepoch('now','-1 hours')+3)*1000 AS INTEGER)),
  ('seed-002', 'sent',    '["bob@company.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',          'Verify your email address',        '<seed-002@acme.io>', NULL, NULL, CAST(unixepoch('now','-2 hours')*1000 AS INTEGER), CAST((unixepoch('now','-2 hours')+2)*1000 AS INTEGER)),
  ('seed-003', 'sent',    '["carol@startup.io"]',  '{"email":"billing@acme.io","name":"Acme Billing"}',  'Invoice #1042 from Acme',          '<seed-003@acme.io>', NULL, NULL, CAST(unixepoch('now','-3 hours')*1000 AS INTEGER), CAST((unixepoch('now','-3 hours')+4)*1000 AS INTEGER)),
  ('seed-004', 'failed',  '["dave@example.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Your password has been reset',     NULL, 'RECIPIENT_REJECTED', 'The recipient address was rejected by the server', CAST(unixepoch('now','-4 hours')*1000 AS INTEGER), NULL),
  ('seed-005', 'sent',    '["eve@techcorp.io"]',   '{"email":"security@acme.io","name":"Acme Security"}','Security alert: New sign-in',      '<seed-005@acme.io>', NULL, NULL, CAST(unixepoch('now','-5 hours')*1000 AS INTEGER), CAST((unixepoch('now','-5 hours')+2)*1000 AS INTEGER)),
  ('seed-006', 'pending', '["frank@agency.net"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Action required: Confirm your subscription', NULL, NULL, NULL, CAST(unixepoch('now','-30 minutes')*1000 AS INTEGER), NULL);

-- ── Day 1 ────────────────────────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-010', 'sent', '["grace@dev.io"]',      '{"email":"noreply@acme.io","name":"Acme"}',         'Welcome to Acme',               '<seed-010@acme.io>', NULL, NULL, CAST(unixepoch('now','-1 days','+9 hours')*1000 AS INTEGER), CAST((unixepoch('now','-1 days','+9 hours')+2)*1000 AS INTEGER)),
  ('seed-011', 'sent', '["henry@corp.com"]',    '{"email":"noreply@acme.io","name":"Acme"}',         'Verify your email address',     '<seed-011@acme.io>', NULL, NULL, CAST(unixepoch('now','-1 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-1 days','+10 hours')+3)*1000 AS INTEGER)),
  ('seed-012', 'sent', '["alice@gmail.com"]',   '{"email":"billing@acme.io","name":"Acme Billing"}',' Invoice #1043 from Acme',      '<seed-012@acme.io>', NULL, NULL, CAST(unixepoch('now','-1 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-1 days','+11 hours')+4)*1000 AS INTEGER)),
  ('seed-013', 'sent', '["bob@company.com"]',   '{"email":"security@acme.io","name":"Acme Security"}','Security alert: New sign-in',  '<seed-013@acme.io>', NULL, NULL, CAST(unixepoch('now','-1 days','+13 hours')*1000 AS INTEGER), CAST((unixepoch('now','-1 days','+13 hours')+2)*1000 AS INTEGER)),
  ('seed-014', 'sent', '["carol@startup.io"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Your trial expires in 3 days',  '<seed-014@acme.io>', NULL, NULL, CAST(unixepoch('now','-1 days','+14 hours')*1000 AS INTEGER), CAST((unixepoch('now','-1 days','+14 hours')+3)*1000 AS INTEGER)),
  ('seed-015', 'failed','["ivan@nowhere.xyz"]', '{"email":"noreply@acme.io","name":"Acme"}',         'Welcome to Acme',               NULL, 'SENDING_DOMAIN_NOT_VERIFIED', 'The sending domain is not verified', CAST(unixepoch('now','-1 days','+15 hours')*1000 AS INTEGER), NULL);

-- ── Day 2 ────────────────────────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-020', 'sent', '["dave@example.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Your order #8521 has shipped',   '<seed-020@acme.io>', NULL, NULL, CAST(unixepoch('now','-2 days','+8 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-2 days','+8 hours')+5)*1000 AS INTEGER)),
  ('seed-021', 'sent', '["eve@techcorp.io"]',   '{"email":"noreply@acme.io","name":"Acme"}',         'Your password has been reset',   '<seed-021@acme.io>', NULL, NULL, CAST(unixepoch('now','-2 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-2 days','+10 hours')+2)*1000 AS INTEGER)),
  ('seed-022', 'sent', '["frank@agency.net"]',  '{"email":"billing@acme.io","name":"Acme Billing"}',' Invoice #1044 from Acme',       '<seed-022@acme.io>', NULL, NULL, CAST(unixepoch('now','-2 days','+12 hours')*1000 AS INTEGER), CAST((unixepoch('now','-2 days','+12 hours')+4)*1000 AS INTEGER)),
  ('seed-023', 'sent', '["grace@dev.io"]',      '{"email":"noreply@acme.io","name":"Acme"}',         'Account verification required',  '<seed-023@acme.io>', NULL, NULL, CAST(unixepoch('now','-2 days','+14 hours')*1000 AS INTEGER), CAST((unixepoch('now','-2 days','+14 hours')+3)*1000 AS INTEGER)),
  ('seed-024', 'failed','["henry@corp.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',         'New team member added',          NULL, 'RATE_LIMITED', 'Too many requests, please try again later', CAST(unixepoch('now','-2 days','+16 hours')*1000 AS INTEGER), NULL);

-- ── Day 3 ────────────────────────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-030', 'sent', '["alice@gmail.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',          'Monthly report — April 2026',   '<seed-030@acme.io>', NULL, NULL, CAST(unixepoch('now','-3 days','+9 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-3 days','+9 hours')+3)*1000 AS INTEGER)),
  ('seed-031', 'sent', '["bob@company.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',          'Welcome to Acme',               '<seed-031@acme.io>', NULL, NULL, CAST(unixepoch('now','-3 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-3 days','+10 hours')+2)*1000 AS INTEGER)),
  ('seed-032', 'sent', '["carol@startup.io"]',  '{"email":"security@acme.io","name":"Acme Security"}',' Security alert: New sign-in',  '<seed-032@acme.io>', NULL, NULL, CAST(unixepoch('now','-3 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-3 days','+11 hours')+2)*1000 AS INTEGER)),
  ('seed-033', 'failed','["junk@badinput"]',    '{"email":"noreply@acme.io","name":"Acme"}',          'Verify your email address',     NULL, 'RECIPIENT_REJECTED', 'The recipient address was rejected by the server', CAST(unixepoch('now','-3 days','+13 hours')*1000 AS INTEGER), NULL),
  ('seed-034', 'sent', '["dave@example.com"]',  '{"email":"billing@acme.io","name":"Acme Billing"}',  'Invoice #1045 from Acme',       '<seed-034@acme.io>', NULL, NULL, CAST(unixepoch('now','-3 days','+15 hours')*1000 AS INTEGER), CAST((unixepoch('now','-3 days','+15 hours')+4)*1000 AS INTEGER)),
  ('seed-035', 'failed','["eve@techcorp.io"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Your trial expires in 3 days',  NULL, 'SENDING_DOMAIN_NOT_VERIFIED', 'The sending domain is not verified', CAST(unixepoch('now','-3 days','+16 hours')*1000 AS INTEGER), NULL);

-- ── Day 4 ────────────────────────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-040', 'sent', '["frank@agency.net"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Your order #8534 has shipped',  '<seed-040@acme.io>', NULL, NULL, CAST(unixepoch('now','-4 days','+9 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-4 days','+9 hours')+5)*1000 AS INTEGER)),
  ('seed-041', 'sent', '["grace@dev.io"]',      '{"email":"noreply@acme.io","name":"Acme"}',          'Welcome to Acme',               '<seed-041@acme.io>', NULL, NULL, CAST(unixepoch('now','-4 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-4 days','+11 hours')+2)*1000 AS INTEGER)),
  ('seed-042', 'sent', '["henry@corp.com"]',    '{"email":"noreply@acme.io","name":"Acme"}',          'Password reset requested',      '<seed-042@acme.io>', NULL, NULL, CAST(unixepoch('now','-4 days','+14 hours')*1000 AS INTEGER), CAST((unixepoch('now','-4 days','+14 hours')+2)*1000 AS INTEGER)),
  ('seed-043', 'sent', '["alice@gmail.com"]',   '{"email":"security@acme.io","name":"Acme Security"}',' Security alert: New sign-in',  '<seed-043@acme.io>', NULL, NULL, CAST(unixepoch('now','-4 days','+16 hours')*1000 AS INTEGER), CAST((unixepoch('now','-4 days','+16 hours')+2)*1000 AS INTEGER));

-- ── Day 5 ────────────────────────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-050', 'sent', '["bob@company.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',          'Verify your email address',     '<seed-050@acme.io>', NULL, NULL, CAST(unixepoch('now','-5 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-5 days','+10 hours')+3)*1000 AS INTEGER)),
  ('seed-051', 'sent', '["carol@startup.io"]',  '{"email":"billing@acme.io","name":"Acme Billing"}',  'Invoice #1046 from Acme',       '<seed-051@acme.io>', NULL, NULL, CAST(unixepoch('now','-5 days','+12 hours')*1000 AS INTEGER), CAST((unixepoch('now','-5 days','+12 hours')+4)*1000 AS INTEGER)),
  ('seed-052', 'sent', '["dave@example.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'New team member added',         '<seed-052@acme.io>', NULL, NULL, CAST(unixepoch('now','-5 days','+13 hours')*1000 AS INTEGER), CAST((unixepoch('now','-5 days','+13 hours')+2)*1000 AS INTEGER)),
  ('seed-053', 'failed','["eve@techcorp.io"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Monthly report — April 2026',   NULL, 'RATE_LIMITED', 'Too many requests, please try again later', CAST(unixepoch('now','-5 days','+15 hours')*1000 AS INTEGER), NULL),
  ('seed-054', 'sent', '["frank@agency.net"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Your trial expires in 3 days',  '<seed-054@acme.io>', NULL, NULL, CAST(unixepoch('now','-5 days','+16 hours')*1000 AS INTEGER), CAST((unixepoch('now','-5 days','+16 hours')+3)*1000 AS INTEGER));

-- ── Day 6 ────────────────────────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-060', 'sent', '["grace@dev.io"]',      '{"email":"noreply@acme.io","name":"Acme"}',          'Welcome to Acme',               '<seed-060@acme.io>', NULL, NULL, CAST(unixepoch('now','-6 days','+9 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-6 days','+9 hours')+2)*1000 AS INTEGER)),
  ('seed-061', 'sent', '["henry@corp.com"]',    '{"email":"security@acme.io","name":"Acme Security"}',' Security alert: New sign-in',  '<seed-061@acme.io>', NULL, NULL, CAST(unixepoch('now','-6 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-6 days','+11 hours')+2)*1000 AS INTEGER)),
  ('seed-062', 'sent', '["alice@gmail.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',          'Your order #8540 has shipped',  '<seed-062@acme.io>', NULL, NULL, CAST(unixepoch('now','-6 days','+14 hours')*1000 AS INTEGER), CAST((unixepoch('now','-6 days','+14 hours')+5)*1000 AS INTEGER));

-- ── Days 7–13 (medium volume) ────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-070', 'sent',   '["bob@company.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Verify your email address',     '<seed-070@acme.io>', NULL, NULL, CAST(unixepoch('now','-7 days','+10 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-7 days','+10 hours')+3)*1000 AS INTEGER)),
  ('seed-071', 'sent',   '["carol@startup.io"]', '{"email":"noreply@acme.io","name":"Acme"}',         'Welcome to Acme',               '<seed-071@acme.io>', NULL, NULL, CAST(unixepoch('now','-7 days','+13 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-7 days','+13 hours')+2)*1000 AS INTEGER)),
  ('seed-072', 'failed', '["broken@x.z"]',       '{"email":"noreply@acme.io","name":"Acme"}',         'Invoice #1047 from Acme',       NULL, 'RECIPIENT_REJECTED', 'The recipient address was rejected by the server', CAST(unixepoch('now','-7 days','+15 hours')*1000 AS INTEGER), NULL),
  ('seed-080', 'sent',   '["dave@example.com"]', '{"email":"billing@acme.io","name":"Acme Billing"}', 'Invoice #1048 from Acme',       '<seed-080@acme.io>', NULL, NULL, CAST(unixepoch('now','-8 days','+9 hours')*1000 AS INTEGER),   CAST((unixepoch('now','-8 days','+9 hours')+4)*1000 AS INTEGER)),
  ('seed-081', 'sent',   '["eve@techcorp.io"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Password reset requested',      '<seed-081@acme.io>', NULL, NULL, CAST(unixepoch('now','-8 days','+12 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-8 days','+12 hours')+2)*1000 AS INTEGER)),
  ('seed-090', 'sent',   '["frank@agency.net"]', '{"email":"noreply@acme.io","name":"Acme"}',         'Your trial expires in 3 days',  '<seed-090@acme.io>', NULL, NULL, CAST(unixepoch('now','-9 days','+10 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-9 days','+10 hours')+3)*1000 AS INTEGER)),
  ('seed-091', 'sent',   '["grace@dev.io"]',     '{"email":"security@acme.io","name":"Acme Security"}','Security alert: New sign-in',  '<seed-091@acme.io>', NULL, NULL, CAST(unixepoch('now','-9 days','+14 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-9 days','+14 hours')+2)*1000 AS INTEGER)),
  ('seed-092', 'failed', '["henry@corp.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',         'Monthly report — April 2026',   NULL, 'RATE_LIMITED', 'Too many requests, please try again later', CAST(unixepoch('now','-9 days','+16 hours')*1000 AS INTEGER), NULL),
  ('seed-100', 'sent',   '["alice@gmail.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Account verification required', '<seed-100@acme.io>', NULL, NULL, CAST(unixepoch('now','-10 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-10 days','+11 hours')+3)*1000 AS INTEGER)),
  ('seed-110', 'sent',   '["bob@company.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Welcome to Acme',               '<seed-110@acme.io>', NULL, NULL, CAST(unixepoch('now','-11 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-11 days','+10 hours')+2)*1000 AS INTEGER)),
  ('seed-111', 'sent',   '["carol@startup.io"]', '{"email":"billing@acme.io","name":"Acme Billing"}', 'Invoice #1049 from Acme',       '<seed-111@acme.io>', NULL, NULL, CAST(unixepoch('now','-11 days','+13 hours')*1000 AS INTEGER), CAST((unixepoch('now','-11 days','+13 hours')+4)*1000 AS INTEGER)),
  ('seed-120', 'sent',   '["dave@example.com"]', '{"email":"noreply@acme.io","name":"Acme"}',         'New team member added',         '<seed-120@acme.io>', NULL, NULL, CAST(unixepoch('now','-12 days','+9 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-12 days','+9 hours')+2)*1000 AS INTEGER)),
  ('seed-121', 'failed', '["typo@.invalid"]',    '{"email":"noreply@acme.io","name":"Acme"}',         'Verify your email address',     NULL, 'RECIPIENT_REJECTED', 'The recipient address was rejected by the server', CAST(unixepoch('now','-12 days','+11 hours')*1000 AS INTEGER), NULL),
  ('seed-130', 'sent',   '["eve@techcorp.io"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Your order #8561 has shipped',  '<seed-130@acme.io>', NULL, NULL, CAST(unixepoch('now','-13 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-13 days','+10 hours')+5)*1000 AS INTEGER));

-- ── Days 14–20 (lower volume) ────────────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-140', 'sent',   '["frank@agency.net"]', '{"email":"noreply@acme.io","name":"Acme"}',          'Welcome to Acme',              '<seed-140@acme.io>', NULL, NULL, CAST(unixepoch('now','-14 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-14 days','+10 hours')+2)*1000 AS INTEGER)),
  ('seed-141', 'sent',   '["grace@dev.io"]',     '{"email":"security@acme.io","name":"Acme Security"}',' Security alert: New sign-in', '<seed-141@acme.io>', NULL, NULL, CAST(unixepoch('now','-14 days','+14 hours')*1000 AS INTEGER), CAST((unixepoch('now','-14 days','+14 hours')+2)*1000 AS INTEGER)),
  ('seed-150', 'sent',   '["henry@corp.com"]',   '{"email":"billing@acme.io","name":"Acme Billing"}',  'Invoice #1050 from Acme',      '<seed-150@acme.io>', NULL, NULL, CAST(unixepoch('now','-15 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-15 days','+11 hours')+4)*1000 AS INTEGER)),
  ('seed-151', 'failed', '["nobody@lost.net"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Your trial expires in 3 days', NULL, 'SENDING_DOMAIN_NOT_VERIFIED', 'The sending domain is not verified', CAST(unixepoch('now','-15 days','+13 hours')*1000 AS INTEGER), NULL),
  ('seed-160', 'sent',   '["alice@gmail.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Password reset requested',     '<seed-160@acme.io>', NULL, NULL, CAST(unixepoch('now','-16 days','+9 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-16 days','+9 hours')+2)*1000 AS INTEGER)),
  ('seed-170', 'sent',   '["bob@company.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',          'Monthly report — March 2026',  '<seed-170@acme.io>', NULL, NULL, CAST(unixepoch('now','-17 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-17 days','+10 hours')+3)*1000 AS INTEGER)),
  ('seed-180', 'sent',   '["carol@startup.io"]', '{"email":"noreply@acme.io","name":"Acme"}',          'Welcome to Acme',              '<seed-180@acme.io>', NULL, NULL, CAST(unixepoch('now','-18 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-18 days','+11 hours')+2)*1000 AS INTEGER)),
  ('seed-190', 'sent',   '["dave@example.com"]', '{"email":"security@acme.io","name":"Acme Security"}',' Security alert: New sign-in', '<seed-190@acme.io>', NULL, NULL, CAST(unixepoch('now','-19 days','+14 hours')*1000 AS INTEGER), CAST((unixepoch('now','-19 days','+14 hours')+2)*1000 AS INTEGER)),
  ('seed-200', 'sent',   '["eve@techcorp.io"]',  '{"email":"billing@acme.io","name":"Acme Billing"}',  'Invoice #1051 from Acme',      '<seed-200@acme.io>', NULL, NULL, CAST(unixepoch('now','-20 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-20 days','+10 hours')+4)*1000 AS INTEGER));

-- ── Days 21–28 (sparse, trailing off) ────────────────────────────
INSERT INTO email_logs (id, status, to_addresses, from_address, subject, message_id, error_code, error_message, created_at, sent_at) VALUES
  ('seed-210', 'sent', '["frank@agency.net"]', '{"email":"noreply@acme.io","name":"Acme"}',         'New team member added',         '<seed-210@acme.io>', NULL, NULL, CAST(unixepoch('now','-21 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-21 days','+10 hours')+2)*1000 AS INTEGER)),
  ('seed-220', 'sent', '["grace@dev.io"]',     '{"email":"noreply@acme.io","name":"Acme"}',         'Verify your email address',     '<seed-220@acme.io>', NULL, NULL, CAST(unixepoch('now','-22 days','+11 hours')*1000 AS INTEGER), CAST((unixepoch('now','-22 days','+11 hours')+3)*1000 AS INTEGER)),
  ('seed-230', 'sent', '["henry@corp.com"]',   '{"email":"noreply@acme.io","name":"Acme"}',         'Welcome to Acme',               '<seed-230@acme.io>', NULL, NULL, CAST(unixepoch('now','-23 days','+9 hours')*1000 AS INTEGER),  CAST((unixepoch('now','-23 days','+9 hours')+2)*1000 AS INTEGER)),
  ('seed-240', 'sent', '["alice@gmail.com"]',  '{"email":"billing@acme.io","name":"Acme Billing"}',' Invoice #1052 from Acme',      '<seed-240@acme.io>', NULL, NULL, CAST(unixepoch('now','-25 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-25 days','+10 hours')+4)*1000 AS INTEGER)),
  ('seed-250', 'sent', '["bob@company.com"]',  '{"email":"noreply@acme.io","name":"Acme"}',         'Monthly report — March 2026',   '<seed-250@acme.io>', NULL, NULL, CAST(unixepoch('now','-27 days','+10 hours')*1000 AS INTEGER), CAST((unixepoch('now','-27 days','+10 hours')+3)*1000 AS INTEGER));
